on: 
  pull_request:
    branches:
      - master
      - develop

name: SmartFarmooor-test-and-local-deployment

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: ./forge_test.sh

      - name: Check storage conflicts
        run: ./forge_inspect.sh check