name: Test / BTC Lending / Deposit
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Compile
        env:
          INFURA_KEY: ${{ secrets.INFURA_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ACTIONS: ${{ secrets.ACTIONS }}
        run: npx hardhat compile
      - name: Run test
        env:
          INFURA_KEY: ${{ secrets.INFURA_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: npm test test/vault/native/withdrawVault.spec.ts
